/**
 * South African Geographic Data
 * 
 * This file is auto-generated by scripts/source-geographic-data.ts
 * DO NOT EDIT MANUALLY - Run 'bun scripts/source-geographic-data.ts' to regenerate
 * 
 * Last updated: 2025-12-25T11:13:46.203Z
 */

export interface Suburb {
  name: string
  code?: string
}

export interface City {
  name: string
  suburbs: Suburb[]
}

export interface ProvinceData {
  name: string
  cities: City[]
}

export const SOUTH_AFRICAN_GEOGRAPHIC_DATA: Record<string, ProvinceData> = {
  "Western Cape": {
    "name": "Western Cape",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      },
      {
        "name": "Cape Town",
        "suburbs": [
          {
            "name": "Main page"
          },
          {
            "name": "Contents"
          },
          {
            "name": "Current events"
          },
          {
            "name": "Random article"
          },
          {
            "name": "About Wikipedia"
          },
          {
            "name": "Contact us"
          },
          {
            "name": "Help"
          },
          {
            "name": "Learn to edit"
          },
          {
            "name": "Community portal"
          },
          {
            "name": "Recent changes"
          },
          {
            "name": "Upload file"
          },
          {
            "name": "Special pages"
          },
          {
            "name": "Donate"
          },
          {
            "name": "Create account"
          },
          {
            "name": "Log in"
          },
          {
            "name": "1"
          },
          {
            "name": "2"
          },
          {
            "name": "3"
          },
          {
            "name": "4"
          },
          {
            "name": "5"
          },
          {
            "name": "6"
          },
          {
            "name": "7"
          },
          {
            "name": "8"
          },
          {
            "name": "Afrikaans"
          },
          {
            "name": "Deutsch"
          },
          {
            "name": "Italiano"
          },
          {
            "name": "Article"
          },
          {
            "name": "Talk"
          },
          {
            "name": "Read"
          },
          {
            "name": "Edit"
          },
          {
            "name": "View history"
          },
          {
            "name": "What links here"
          },
          {
            "name": "Related changes"
          },
          {
            "name": "Permanent link"
          },
          {
            "name": "Page information"
          },
          {
            "name": "Cite this page"
          },
          {
            "name": "Get shortened URL"
          },
          {
            "name": "Download QR code"
          },
          {
            "name": "Download as PDF"
          },
          {
            "name": "Printable version"
          },
          {
            "name": "Wikidata item"
          },
          {
            "name": "Bakoven"
          },
          {
            "name": "Bantry Bay"
          },
          {
            "name": "Camps Bay"
          },
          {
            "name": "Clifton"
          },
          {
            "name": "Fresnaye"
          },
          {
            "name": "Green Point"
          },
          {
            "name": "Llandudno"
          },
          {
            "name": "Mouille Point"
          },
          {
            "name": "Sea Point"
          },
          {
            "name": "Three Anchor Bay"
          },
          {
            "name": "Atlantis"
          },
          {
            "name": "Bloubergstrand"
          },
          {
            "name": "Brooklyn"
          },
          {
            "name": "Century City"
          },
          {
            "name": "Canal Walk"
          },
          {
            "name": "Dunoon"
          },
          {
            "name": "Duynefontein"
          },
          {
            "name": "Joe Slovo Park"
          },
          {
            "name": "Killarney Gardens"
          },
          {
            "name": "Mamre"
          },
          {
            "name": "Melkbosstrand"
          },
          {
            "name": "Milnerton"
          },
          {
            "name": "Montague Gardens"
          },
          {
            "name": "Paarden Eiland"
          },
          {
            "name": "Parklands"
          },
          {
            "name": "Summer Greens"
          },
          {
            "name": "Table View"
          },
          {
            "name": "Ysterplaat"
          },
          {
            "name": "Athlone"
          },
          {
            "name": "Bishop Lavis"
          },
          {
            "name": "Crawford"
          },
          {
            "name": "Crossroads"
          },
          {
            "name": "Gugulethu"
          },
          {
            "name": "Hanover Park"
          },
          {
            "name": "Heideveld"
          },
          {
            "name": "Kenwyn"
          },
          {
            "name": "Lansdowne"
          },
          {
            "name": "Lavender Hill"
          },
          {
            "name": "Manenberg"
          },
          {
            "name": "Matroosfontein"
          },
          {
            "name": "Nyanga"
          },
          {
            "name": "Ottery"
          },
          {
            "name": "Browns Farm"
          },
          {
            "name": "Philippi Horticultural"
          },
          {
            "name": "Philippi East"
          },
          {
            "name": "Rondebosch East"
          },
          {
            "name": "Strandfontein"
          },
          {
            "name": "Bongweni"
          },
          {
            "name": "Harare/Holimisa"
          },
          {
            "name": "Ikwezi Park"
          },
          {
            "name": "Mandela Park"
          },
          {
            "name": "Griffiths Mxenge"
          },
          {
            "name": "QQ Section"
          },
          {
            "name": "Silver Town"
          },
          {
            "name": "Victoria Merge"
          },
          {
            "name": "Rocklands"
          },
          {
            "name": "Westridge"
          },
          {
            "name": "Portlands"
          },
          {
            "name": "Tafelsig"
          }
        ]
      }
    ]
  },
  "Gauteng": {
    "name": "Gauteng",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "KwaZulu-Natal": {
    "name": "KwaZulu-Natal",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "Eastern Cape": {
    "name": "Eastern Cape",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "Free State": {
    "name": "Free State",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "Mpumalanga": {
    "name": "Mpumalanga",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "Limpopo": {
    "name": "Limpopo",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "North West": {
    "name": "North West",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  },
  "Northern Cape": {
    "name": "Northern Cape",
    "cities": [
      {
        "name": "Akasia",
        "suburbs": []
      },
      {
        "name": "Alberton",
        "suburbs": []
      },
      {
        "name": "Bassonia",
        "suburbs": []
      },
      {
        "name": "Bedfordview",
        "suburbs": []
      },
      {
        "name": "Benoni",
        "suburbs": []
      },
      {
        "name": "Boksburg",
        "suburbs": []
      },
      {
        "name": "Brakpan",
        "suburbs": []
      },
      {
        "name": "Broadacres",
        "suburbs": []
      },
      {
        "name": "Bronkhorstspruit",
        "suburbs": []
      },
      {
        "name": "Bryanston",
        "suburbs": []
      },
      {
        "name": "Carletonville",
        "suburbs": []
      },
      {
        "name": "Centurion",
        "suburbs": []
      },
      {
        "name": "Cullinan",
        "suburbs": []
      },
      {
        "name": "Dainfern",
        "suburbs": []
      },
      {
        "name": "Die Hoewes",
        "suburbs": []
      },
      {
        "name": "Edenvale",
        "suburbs": []
      },
      {
        "name": "Eikenhof",
        "suburbs": []
      },
      {
        "name": "Eldoraigne",
        "suburbs": []
      },
      {
        "name": "Equestria",
        "suburbs": []
      },
      {
        "name": "Evaton",
        "suburbs": []
      },
      {
        "name": "Faerie Glen",
        "suburbs": []
      },
      {
        "name": "Fochville",
        "suburbs": []
      },
      {
        "name": "Fourways",
        "suburbs": []
      },
      {
        "name": "Ga-rankuwa",
        "suburbs": []
      },
      {
        "name": "Germiston",
        "suburbs": []
      },
      {
        "name": "Glenvista",
        "suburbs": []
      },
      {
        "name": "Hammanskraal",
        "suburbs": []
      },
      {
        "name": "Heidelberg",
        "suburbs": []
      },
      {
        "name": "Highveld",
        "suburbs": []
      },
      {
        "name": "Johannesburg",
        "suburbs": []
      },
      {
        "name": "Katlehong",
        "suburbs": []
      },
      {
        "name": "Kempton Park",
        "suburbs": []
      },
      {
        "name": "Kensington",
        "suburbs": []
      },
      {
        "name": "Krugersdorp",
        "suburbs": []
      },
      {
        "name": "Lonehill",
        "suburbs": []
      },
      {
        "name": "Mabopane",
        "suburbs": []
      },
      {
        "name": "Meyerton",
        "suburbs": []
      },
      {
        "name": "Midlands Estate",
        "suburbs": []
      },
      {
        "name": "Midrand",
        "suburbs": []
      },
      {
        "name": "Mondeor",
        "suburbs": []
      },
      {
        "name": "Montana",
        "suburbs": []
      },
      {
        "name": "Morningside",
        "suburbs": []
      },
      {
        "name": "Mulbarton",
        "suburbs": []
      },
      {
        "name": "Nigel",
        "suburbs": []
      },
      {
        "name": "Pretoria",
        "suburbs": []
      },
      {
        "name": "Randburg",
        "suburbs": []
      },
      {
        "name": "Randfontein",
        "suburbs": []
      },
      {
        "name": "Rayton",
        "suburbs": []
      },
      {
        "name": "Roodepoort",
        "suburbs": []
      },
      {
        "name": "Sandton",
        "suburbs": []
      },
      {
        "name": "Sebokeng",
        "suburbs": []
      },
      {
        "name": "Soshanguve",
        "suburbs": []
      },
      {
        "name": "Soweto",
        "suburbs": []
      },
      {
        "name": "Springs",
        "suburbs": []
      },
      {
        "name": "Sunninghill",
        "suburbs": []
      },
      {
        "name": "Temba",
        "suburbs": []
      },
      {
        "name": "Tembisa",
        "suburbs": []
      },
      {
        "name": "The Reeds",
        "suburbs": []
      },
      {
        "name": "Vaal Marina",
        "suburbs": []
      },
      {
        "name": "Vanderbijlpark",
        "suburbs": []
      },
      {
        "name": "Vereeniging",
        "suburbs": []
      },
      {
        "name": "Walkerville",
        "suburbs": []
      },
      {
        "name": "Waterkloof Ridge",
        "suburbs": []
      },
      {
        "name": "Westonaria",
        "suburbs": []
      },
      {
        "name": "Wierda Park",
        "suburbs": []
      },
      {
        "name": "Winchester Hills",
        "suburbs": []
      },
      {
        "name": "Wonderboom",
        "suburbs": []
      }
    ]
  }
} as const
