"use client"

import { useState } from "react"
import { type SelectBillingPeriod } from "@/db/schema"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ChevronDown, ChevronUp, FileText, DollarSign, AlertCircle } from "lucide-react"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"

interface PeriodCardProps {
  period: SelectBillingPeriod
  periodType: "invoice" | "payable"
  propertyId: string
}

export function PeriodCard({ period, periodType, propertyId }: PeriodCardProps) {
  const [expanded, setExpanded] = useState(false)
  const [matchedBills, setMatchedBills] = useState<Array<{
    id: string
    fileName: string
    billType: string
    status: string
    [key: string]: unknown
  }>>([])
  const [loading, setLoading] = useState(false)

  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ]

  const periodLabel = `${monthNames[period.periodMonth - 1]} ${period.periodYear}`

  const handleExpand = async () => {
    if (!expanded && matchedBills.length === 0) {
      setLoading(true)
      try {
        const response = await fetch(`/api/billing-schedule/periods/${period.id}/bills`)
        const data = await response.json()
        if (data.success) {
          setMatchedBills(data.bills || [])
        }
      } catch (error) {
        console.error("Error fetching bills for period:", error)
      } finally {
        setLoading(false)
      }
    }
    setExpanded(!expanded)
  }

  // Determine status
  const now = new Date()
  const periodEnd = new Date(period.periodEndDate)
  const isPast = periodEnd < now
  const isCurrent = new Date(period.periodStartDate) <= now && periodEnd >= now

  const statusBadge =
    isPast && matchedBills.length === 0 ? (
      <Badge variant="destructive">Late</Badge>
    ) : isPast ? (
      <Badge variant="secondary">Complete</Badge>
    ) : isCurrent ? (
      <Badge className="bg-yellow-600 text-white">Current</Badge>
    ) : (
      <Badge variant="outline">Upcoming</Badge>
    )

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
            <div className={`rounded-lg p-2 ${periodType === "invoice" ? "bg-blue-100 dark:bg-blue-900" : "bg-green-100 dark:bg-green-900"}`}>
              {periodType === "invoice" ? (
                <FileText className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              ) : (
                <DollarSign className="h-5 w-5 text-green-600 dark:text-green-400" />
              )}
            </div>
            <div>
              <CardTitle className="text-lg">{periodLabel}</CardTitle>
              <div className="flex items-center gap-2 mt-1">
                <Badge variant={periodType === "invoice" ? "default" : "secondary"}>
                  {periodType === "invoice" ? "Invoice" : "Payable"}
                </Badge>
                {statusBadge}
                <Badge variant="outline" className="text-xs">
                  {matchedBills.length} bill{matchedBills.length !== 1 ? "s" : ""}
                </Badge>
              </div>
            </div>
          </div>
          <Collapsible open={expanded} onOpenChange={setExpanded}>
            <CollapsibleTrigger asChild>
              <Button variant="ghost" size="icon" onClick={handleExpand}>
                {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent>
              <CardContent className="pt-0">
                <div className="space-y-4 pt-4 border-t">
                  <div>
                    <p className="text-sm font-medium mb-2">Period Details</p>
                    <div className="text-sm text-muted-foreground space-y-1">
                      <p>
                        Start: {new Date(period.periodStartDate).toLocaleDateString()}
                      </p>
                      <p>
                        End: {new Date(period.periodEndDate).toLocaleDateString()}
                      </p>
                      <p>
                        Generated by: {period.generationSource === "lease_upload" ? "Lease Upload" : period.generationSource === "manual" ? "Manual" : "Cron Job"}
                      </p>
                    </div>
                  </div>

                  {loading ? (
                    <div className="text-center py-4 text-muted-foreground text-sm">Loading bills...</div>
                  ) : matchedBills.length > 0 ? (
                    <div>
                      <p className="text-sm font-medium mb-2">Matched Bills</p>
                      <div className="space-y-2">
                        {matchedBills.map((bill) => (
                          <div
                            key={bill.id}
                            className="flex items-center justify-between rounded-md border p-2"
                          >
                            <div className="flex items-center gap-2">
                              <FileText className="h-4 w-4 text-muted-foreground" />
                              <span className="text-sm">{bill.fileName}</span>
                              <Badge variant="outline" className="text-xs capitalize">
                                {bill.billType}
                              </Badge>
                            </div>
                            <Badge
                              variant={bill.status === "processed" ? "default" : "secondary"}
                              className="text-xs"
                            >
                              {bill.status}
                            </Badge>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-4 text-muted-foreground text-sm">
                      <AlertCircle className="h-8 w-8 mx-auto mb-2 opacity-50" />
                      <p>No bills matched to this period</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </CardHeader>
    </Card>
  )
}

